# Generated by Django 5.0.1 on 2024-02-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='id_producto',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='id_producto',
            field=models.ManyToManyField(to='Project.producto', verbose_name='Producto'),
        ),
    ]
