# Generated by Django 4.0.2 on 2024-02-13 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_remove_solicitud_id_producto_solicitud_id_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='id_producto',
            field=models.ManyToManyField(to='Project.Producto', verbose_name='Producto'),
        ),
    ]
